MCU = atmega32u4
BOOTLOADER = caterina


OPT = s
LTO_ENABLE = yes
EXTRAFLAGS += -flto

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
WPM_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
AUDIO_ENABLE = no
MUSIC_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
RGB_MATRIX_ENABLE = no
LED_MATRIX_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
TRI_LAYER_ENABLE = no
LAYER_LOCK_ENABLE = no
CAPS_WORD_ENABLE = no
REPEAT_KEY_ENABLE = no

CUSTOM_MATRIX = no

DEBOUNCE_TYPE = sym_defer_pk
SPLIT_KEYBOARD = no
WAIT_FOR_USB = no
